# -*- coding: utf-8 -*-
"""SCRAPING_A387YBM185.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZjlmS-390YvRX9ghXBxLTbhooYXnmCg
"""

!pip install google-play-scraper

from google_play_scraper import reviews, Sort
import pandas as pd

shopee_reviews, _ = reviews(
    'com.shopee.id',               # package name Shopee Indonesia
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count = 30000,
    filter_score_with=5
)

df = pd.DataFrame(shopee_reviews)
df.to_csv('Ulasan_SHOPEE.csv', index=False)